version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/opt/store-api
    links:
      - db:mongodb
    container_name: store-web
  db:
    image: mongo:3.0.2
    container_name: store-db
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: store-es
