version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/opt/store-api
    links:
      - db:mongodb
    container_name: store-web
    networks:
            frontend:
                ipv4_address: 172.20.0.5
  db:
    image: mongo:3.0.2
    container_name: store-db
    networks:
            frontend:
                ipv4_address: 172.20.0.7
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: store-es
    networks:
            frontend:
                ipv4_address: 172.20.0.8
  kafka:
    build: ./kafka_server
    ports:
      - '9092:9092'
    environment:
      - ADVERTISED_HOST=172.20.0.6
      - ADVERTISED_PORT=9092
    container_name: store-kafka
    networks:
            frontend:
                ipv4_address: 172.20.0.6

  spark:
    build: ./spark_server
    ports:
      - '8888:8888'
    volumes:
      - ./spark_server:/home/code
      - ../data:/home/data
    container_name: store-spark
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 pyspark-shell org.mongodb.spark:mongo-spark-connector_2.11:2.2.3
    networks:
            frontend:
                ipv4_address: 172.20.0.9

  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: store-redis
    networks:
            frontend:
                ipv4_address: 172.20.0.4


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
